#!/usr/bin/env python3
"""
KAGI PCB Gerber Generator
Generates RS-274X Gerber files + drill file for JLCPCB ordering.
Output: manufacturing/gerbers/kagi-lite/*.gbr + *.drl → zipped for JLCPCB upload

Board: KAGI Lite 55×55mm 4-layer PCB
Components placed per CPL-JLCPCB.csv coordinates.
"""

import os
import math
import zipfile
from datetime import datetime

# ── Board dimensions ──────────────────────────────────────────────────────────
BOARD_W  = 55.0   # mm
BOARD_H  = 55.0   # mm
CORNER_R = 1.5    # mm corner radius

# ── Coordinate helpers ────────────────────────────────────────────────────────
def gv(mm: float) -> int:
    """Convert mm to Gerber units (6 decimal places)."""
    return int(round(mm * 1_000_000))

def gxy(x: float, y: float) -> str:
    """Format X/Y Gerber coordinate pair."""
    return f"X{gv(x):09d}Y{gv(y):09d}"

# ── Gerber file header / footer ───────────────────────────────────────────────
def gerber_header(file_function: str, polarity: str = "Positive") -> str:
    now = datetime.now().strftime("%Y-%m-%dT%H:%M:%S+09:00")
    return (
        f"G04 KAGI Lite PCB — {file_function}*\n"
        f"G04 Generated by KAGI Manufacturing Tools {datetime.now().strftime('%Y-%m-%d')}*\n"
        "%FSLAX36Y36*%\n"
        "%MOMM*%\n"
        f"%TF.GenerationSoftware,KAGIGen,1.0,kagi-pcb-generator*%\n"
        f"%TF.CreationDate,{now}*%\n"
        f"%TF.ProjectId,kagi-lite,b2000000-0000-0000-0000-000000000001,1.0*%\n"
        f"%TF.FileFunction,{file_function}*%\n"
        f"%TF.FilePolarity,{polarity}*%\n"
        "%LPD*%\n"
    )

GERBER_FOOTER = "M02*\n"

# ── Aperture definitions ──────────────────────────────────────────────────────
class ApertureLib:
    """Manages aperture definitions for a Gerber file."""
    def __init__(self):
        self._apertures: dict[str, int] = {}
        self._next_id = 10

    def get(self, shape: str, *dims) -> int:
        key = f"{shape}:{','.join(str(d) for d in dims)}"
        if key not in self._apertures:
            self._apertures[key] = self._next_id
            self._next_id += 1
        return self._apertures[key]

    def define_circle(self, d: float) -> int:
        return self.get("C", d)

    def define_rect(self, w: float, h: float) -> int:
        return self.get("R", w, h)

    def define_obround(self, w: float, h: float) -> int:
        return self.get("O", w, h)

    def definitions(self) -> str:
        lines = []
        for key, aid in self._apertures.items():
            shape, *dims = key.split(":")
            vals = dims[0].split(",")
            if shape == "C":
                lines.append(f"%ADD{aid}C,{vals[0]}*%")
            elif shape == "R":
                lines.append(f"%ADD{aid}R,{vals[0]}X{vals[1]}*%")
            elif shape == "O":
                lines.append(f"%ADD{aid}O,{vals[0]}X{vals[1]}*%")
        return "\n".join(lines) + "\n"


# ── Component footprint pad data ───────────────────────────────────────────────
# Each footprint returns list of (dx, dy, w, h, shape) where dx/dy are offsets from centre
# shape: "rect", "circle", "obround"

def pads_0402() -> list:
    """Standard 0402 SMD (R, C, FB): two 0.5×0.6mm pads, 1.0mm pitch."""
    return [(-0.50, 0.0, 0.5, 0.6, "rect"), (0.50, 0.0, 0.5, 0.6, "rect")]

def pads_0603() -> list:
    return [(-0.80, 0.0, 0.8, 0.9, "rect"), (0.80, 0.0, 0.8, 0.9, "rect")]

def pads_sod123() -> list:
    """SOD-123 (D2): two 0.9×1.2mm pads, 2.5mm pitch."""
    return [(-1.25, 0.0, 0.9, 1.2, "rect"), (1.25, 0.0, 0.9, 1.2, "rect")]

def pads_sot23_5() -> list:
    """SOT-23-5 (U5 RT9013): 5 pads."""
    return [
        (-1.0, -1.0, 0.6, 0.9, "rect"),
        (-1.0,  0.0, 0.6, 0.9, "rect"),
        (-1.0,  1.0, 0.6, 0.9, "rect"),
        ( 1.0,  0.5, 0.6, 0.9, "rect"),
        ( 1.0, -0.5, 0.6, 0.9, "rect"),
    ]

def pads_sot23_6() -> list:
    """SOT-23-6 / SOT-363 (U6, D3): 6 pads."""
    return [
        (-1.0, -1.0, 0.6, 0.9, "rect"),
        (-1.0,  0.0, 0.6, 0.9, "rect"),
        (-1.0,  1.0, 0.6, 0.9, "rect"),
        ( 1.0,  1.0, 0.6, 0.9, "rect"),
        ( 1.0,  0.0, 0.6, 0.9, "rect"),
        ( 1.0, -1.0, 0.6, 0.9, "rect"),
    ]

def pads_dfn4() -> list:
    """DFN-4 1.5×1.5mm (U2 SHT40)."""
    return [
        (-0.50, -0.4, 0.5, 0.3, "rect"),
        (-0.50,  0.4, 0.5, 0.3, "rect"),
        ( 0.50,  0.4, 0.5, 0.3, "rect"),
        ( 0.50, -0.4, 0.5, 0.3, "rect"),
    ]

def pads_udfn8() -> list:
    """UDFN-8 2×3mm 0.65mm pitch (U4 ATECC608A)."""
    pitch = 0.65
    return [
        (-0.85, -pitch * 1.5, 0.35, 0.45, "rect"),
        (-0.85, -pitch * 0.5, 0.35, 0.45, "rect"),
        (-0.85,  pitch * 0.5, 0.35, 0.45, "rect"),
        (-0.85,  pitch * 1.5, 0.35, 0.45, "rect"),
        ( 0.85,  pitch * 1.5, 0.35, 0.45, "rect"),
        ( 0.85,  pitch * 0.5, 0.35, 0.45, "rect"),
        ( 0.85, -pitch * 0.5, 0.35, 0.45, "rect"),
        ( 0.85, -pitch * 1.5, 0.35, 0.45, "rect"),
    ]

def pads_ws2812b_2020() -> list:
    """WS2812B-2020 PLCC4 2×2mm: 4 corner pads."""
    return [
        (-0.7, -0.55, 0.7, 0.5, "rect"),
        ( 0.7, -0.55, 0.7, 0.5, "rect"),
        ( 0.7,  0.55, 0.7, 0.5, "rect"),
        (-0.7,  0.55, 0.7, 0.5, "rect"),
    ]

def pads_sw_pts125() -> list:
    """12mm tactile button PTS125: 4 THT pads at corners."""
    return [
        (-3.5, -3.5, 2.2, 2.2, "circle"),
        ( 3.5, -3.5, 2.2, 2.2, "circle"),
        (-3.5,  3.5, 2.2, 2.2, "circle"),
        ( 3.5,  3.5, 2.2, 2.2, "circle"),
    ]

def pads_sw_tl3342() -> list:
    """3×4mm tact SW1 reset: 4 SMD pads."""
    return [
        (-1.6, -1.3, 0.9, 1.8, "rect"),
        ( 1.6, -1.3, 0.9, 1.8, "rect"),
        (-1.6,  1.3, 0.9, 1.8, "rect"),
        ( 1.6,  1.3, 0.9, 1.8, "rect"),
    ]

def pads_jst_ph2() -> list:
    """JST PH 2P B2B-PH-K: 2 THT pads, 2mm pitch."""
    return [(-1.0, 0.0, 1.8, 2.5, "obround"), (1.0, 0.0, 1.8, 2.5, "obround")]

def pads_usbc_hro() -> list:
    """USB-C HRO TYPE-C-31-M-12: SMD + mounting pins.
    Signal pads (top row + bottom row) + 2 mounting THT."""
    pads = []
    # Top signal pads (A-side + B-side combined): 12 pads at 0.5mm pitch
    for i in range(12):
        x = -2.75 + i * 0.5
        pads.append((x, -1.7, 0.25, 0.9, "rect"))
    # 2 mounting/shell pads
    pads.append((-3.5, 0.0, 1.2, 1.6, "rect"))
    pads.append(( 3.5, 0.0, 1.2, 1.6, "rect"))
    return pads

def pads_esp32s3_mini1() -> list:
    """ESP32-S3-MINI-1: castellated pads 15.4×20.4mm module.
    ~18 pads per long side (bottom+sides), 0.8mm pitch."""
    pads = []
    # Bottom row: 18 pads at 0.8mm pitch (9mm span each side of centre)
    for i in range(19):
        x = -7.2 + i * 0.8
        pads.append((x, 10.2, 0.7, 1.0, "rect"))  # bottom
    # Left side: 8 pads
    for i in range(9):
        y = 6.4 - i * 1.6
        pads.append((-7.7, y, 1.0, 0.7, "rect"))
    # Right side: 8 pads
    for i in range(9):
        y = 6.4 - i * 1.6
        pads.append(( 7.7, y, 1.0, 0.7, "rect"))
    return pads

def pads_cr2032_holder() -> list:
    """CR2032 SMD holder Keystone 3034: 2 pads + retention clips."""
    return [
        (-7.0, 0.0, 3.5, 4.0, "rect"),
        ( 7.0, 0.0, 3.5, 4.0, "rect"),
        (-5.0, 5.0, 1.5, 1.5, "rect"),  # retention
        ( 5.0, 5.0, 1.5, 1.5, "rect"),
    ]

def pads_buzzer_tdk() -> list:
    """TDK PS1240P02BT piezo buzzer: 2 THT pads, 12.7mm pitch."""
    return [(-6.35, 0.0, 1.5, 1.5, "circle"), (6.35, 0.0, 1.5, 1.5, "circle")]

def pads_ferrite_bead() -> list:
    return pads_0402()

# ── Component table ───────────────────────────────────────────────────────────
# Keyed by Designator from CPL
COMPONENT_FOOTPRINTS = {
    "U1":  pads_esp32s3_mini1,
    "U2":  pads_dfn4,
    "U3":  pads_jst_ph2,       # LD2410B pin header (simplified)
    "U4":  pads_udfn8,
    "U5":  pads_sot23_5,
    "U6":  pads_sot23_6,
    "J1":  pads_usbc_hro,
    "J2":  pads_jst_ph2,
    "BT1": pads_cr2032_holder,
    "SW1": pads_sw_tl3342,
    "SW2": pads_sw_pts125,
    "D1":  pads_ws2812b_2020,
    "D1b": pads_ws2812b_2020,
    "D2":  pads_sod123,
    "D3":  pads_sot23_6,
    "BZ1": pads_buzzer_tdk,
    "R1":  pads_0402,
    "R2":  pads_0402,
    "R3":  pads_0402,
    "R4":  pads_0402,
    "R5":  pads_0402,
    "R6":  pads_0402,
    "R7":  pads_0402,
    "R8":  pads_0402,
    "C1":  pads_0402,
    "C2":  pads_0402,
    "C3":  pads_0402,
    "C4":  pads_0402,
    "C5":  pads_0402,
    "C6":  pads_0402,
    "FB1": pads_ferrite_bead,
}

# ── CPL data (from CSV) ───────────────────────────────────────────────────────
CPL_DATA = {
    "U1":  (27.5, 28.0, 0),
    "U2":  (45.0, 10.0, 0),
    "U3":  (27.5, 13.0, 0),
    "U4":  (42.0, 42.0, 0),
    "U5":  (20.0, 48.0, 0),
    "U6":  (35.0, 48.0, 0),
    "J1":  (27.5, 52.5, 0),
    "J2":  (52.5, 27.5, 270),
    "BT1": (8.0,  30.0, 0),
    "SW1": (10.0, 48.0, 0),
    "SW2": (27.5, 8.0,  0),
    "D1":  (38.0, 13.0, 0),
    "D1b": (44.0, 13.0, 0),
    "D2":  (8.0,  40.0, 0),
    "D3":  (48.0, 35.0, 0),
    "BZ1": (47.0, 22.0, 0),
    "R1":  (42.0, 18.0, 0),
    "R2":  (42.0, 22.0, 0),
    "R3":  (48.0, 32.0, 0),
    "R4":  (22.0, 51.0, 0),
    "R5":  (33.0, 51.0, 0),
    "R6":  (15.0, 48.0, 0),
    "R7":  (15.0, 44.0, 0),
    "R8":  (38.0, 20.0, 0),
    "C1":  (22.0, 28.0, 0),
    "C2":  (25.0, 28.0, 0),
    "C3":  (20.0, 44.0, 0),
    "C4":  (17.0, 44.0, 0),
    "C5":  (8.0,  22.0, 0),
    "C6":  (32.0, 13.0, 0),
    "FB1": (17.0, 48.0, 0),
}

def rotate(dx: float, dy: float, angle_deg: float) -> tuple[float, float]:
    """Rotate offset by angle (degrees CW in PCB convention)."""
    a = math.radians(angle_deg)
    rx =  dx * math.cos(a) + dy * math.sin(a)
    ry = -dx * math.sin(a) + dy * math.cos(a)
    return rx, ry


# ── Gerber generators ─────────────────────────────────────────────────────────

def gen_edge_cuts() -> str:
    """Generate Edge.Cuts layer: 55×55mm board with 1.5mm corner radius."""
    lib = ApertureLib()
    a_line = lib.define_circle(0.1)  # thin outline line

    lines = [gerber_header("Profile,NP")]
    lines.append(lib.definitions())
    lines.append(f"D{a_line}*")
    lines.append("G01*")  # linear interpolation

    # Board outline as 4 lines (simplified, without arcs for compatibility)
    x0, y0 = 0.0, 0.0
    x1, y1 = BOARD_W, BOARD_H
    corners = [
        (x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0)
    ]
    lines.append(f"{gxy(corners[0][0], corners[0][1])}D02*")
    for cx, cy in corners[1:]:
        lines.append(f"{gxy(cx, cy)}D01*")

    lines.append(GERBER_FOOTER)
    return "\n".join(lines)


def gen_copper_layer(layer_name: str, include_pads: bool = True,
                     is_top: bool = True) -> str:
    """Generate copper layer with component pads."""
    lib = ApertureLib()

    pad_ops = []  # list of (aperture_key, x, y, operation) built after lib populated

    if include_pads:
        for ref, (cx, cy, rot) in CPL_DATA.items():
            fp_func = COMPONENT_FOOTPRINTS.get(ref)
            if not fp_func:
                continue
            for (dx, dy, pw, ph, shape) in fp_func():
                rdx, rdy = rotate(dx, dy, rot)
                px = cx + rdx
                py = cy + rdy
                if shape == "rect":
                    aid = lib.define_rect(pw, ph)
                elif shape == "circle":
                    aid = lib.define_circle(pw)
                elif shape == "obround":
                    aid = lib.define_obround(pw, ph)
                else:
                    aid = lib.define_rect(pw, ph)
                pad_ops.append((aid, px, py))

    func = f"Copper,L1,Top" if is_top else f"Copper,L4,Bot"
    lines = [gerber_header(func)]
    lines.append(lib.definitions())
    lines.append("G01*")

    current_apt = -1
    for (aid, px, py) in pad_ops:
        if aid != current_apt:
            lines.append(f"D{aid}*")
            current_apt = aid
        lines.append(f"{gxy(px, py)}D03*")  # D03 = flash

    lines.append(GERBER_FOOTER)
    return "\n".join(lines)


def gen_copper_inner(layer: int) -> str:
    """Generate empty inner copper layers (GND/PWR planes — unrouted)."""
    lib = ApertureLib()
    a_fill = lib.define_rect(BOARD_W - 1.0, BOARD_H - 1.0)
    func = f"Copper,L{layer},Inr"
    lines = [gerber_header(func)]
    lines.append(lib.definitions())
    lines.append("G01*")
    # Solid copper pour covering the board (GND plane)
    lines.append(f"D{a_fill}*")
    cx, cy = BOARD_W / 2, BOARD_H / 2
    lines.append(f"{gxy(cx, cy)}D03*")
    lines.append(GERBER_FOOTER)
    return "\n".join(lines)


def gen_mask_layer(is_top: bool = True) -> str:
    """Generate solder mask layer (openings at pads, inverted)."""
    lib = ApertureLib()
    MASK_EXP = 0.1  # mask expansion in mm

    pad_ops = []
    for ref, (cx, cy, rot) in CPL_DATA.items():
        fp_func = COMPONENT_FOOTPRINTS.get(ref)
        if not fp_func:
            continue
        for (dx, dy, pw, ph, shape) in fp_func():
            rdx, rdy = rotate(dx, dy, rot)
            px = cx + rdx
            py = cy + rdy
            if shape == "rect":
                aid = lib.define_rect(pw + MASK_EXP, ph + MASK_EXP)
            elif shape == "circle":
                aid = lib.define_circle(pw + MASK_EXP)
            elif shape == "obround":
                aid = lib.define_obround(pw + MASK_EXP, ph + MASK_EXP)
            else:
                aid = lib.define_rect(pw + MASK_EXP, ph + MASK_EXP)
            pad_ops.append((aid, px, py))

    func = "SolderMask,Top" if is_top else "SolderMask,Bot"
    lines = [gerber_header(func, polarity="Negative")]
    lines.append(lib.definitions())
    lines.append("G01*")

    current_apt = -1
    for (aid, px, py) in pad_ops:
        if aid != current_apt:
            lines.append(f"D{aid}*")
            current_apt = aid
        lines.append(f"{gxy(px, py)}D03*")

    lines.append(GERBER_FOOTER)
    return "\n".join(lines)


def gen_silkscreen(is_top: bool = True) -> str:
    """Generate silkscreen with component designators."""
    lib = ApertureLib()
    a_text = lib.define_circle(0.12)  # thin line for text approximation

    func = "Legend,Top" if is_top else "Legend,Bot"
    lines = [gerber_header(func)]
    lines.append(lib.definitions())
    lines.append(f"D{a_text}*")
    lines.append("G01*")

    if is_top:
        # Draw designators as small cross markers at component centres
        for ref, (cx, cy, rot) in CPL_DATA.items():
            half = 0.6
            # Horizontal line
            lines.append(f"{gxy(cx - half, cy)}D02*")
            lines.append(f"{gxy(cx + half, cy)}D01*")
            # Vertical line
            lines.append(f"{gxy(cx, cy - half)}D02*")
            lines.append(f"{gxy(cx, cy + half)}D01*")

        # Board outline on silkscreen
        a_border = lib.define_circle(0.15)
        lines.insert(len(lines) - 1, f"D{a_border}*")
        border = [
            (1.0, 1.0), (54.0, 1.0), (54.0, 54.0), (1.0, 54.0), (1.0, 1.0)
        ]
        lines.append(f"{gxy(border[0][0], border[0][1])}D02*")
        for bx, by in border[1:]:
            lines.append(f"{gxy(bx, by)}D01*")

    lines.append(GERBER_FOOTER)
    return "\n".join(lines)


def gen_drill_file() -> str:
    """Generate Excellon drill file for THT pads and mounting holes."""
    lines = [
        "M48",
        "FMAT,2",
        "METRIC,LZ",
        "TCST,0",
        ";KAGI Lite PCB Drill File",
        ";Generated by KAGI Manufacturing Tools",
        "",
        "T01C0.80  ;Pin headers, JST",
        "T02C1.00  ;Large THT pads (SW2, BZ1)",
        "T03C3.20  ;M3 mounting holes",
        "%",
        "G90",
        "G05",
        "M71",
    ]

    # T01: JST + small THT
    lines.append("T01")
    jst_refs = ["J2"]
    for ref in jst_refs:
        if ref in CPL_DATA:
            cx, cy, rot = CPL_DATA[ref]
            for dx, dy, *_ in COMPONENT_FOOTPRINTS[ref]():
                rdx, rdy = rotate(dx, dy, rot)
                lines.append(f"X{int((cx+rdx)*1000):+07d}Y{int((cy+rdy)*1000):+07d}")

    # T02: SW2 button, BZ1 buzzer
    lines.append("T02")
    tht_refs = ["SW2", "BZ1"]
    for ref in tht_refs:
        if ref in CPL_DATA:
            cx, cy, rot = CPL_DATA[ref]
            for dx, dy, *_ in COMPONENT_FOOTPRINTS[ref]():
                rdx, rdy = rotate(dx, dy, rot)
                lines.append(f"X{int((cx+rdx)*1000):+07d}Y{int((cy+rdy)*1000):+07d}")

    # T03: M3 mounting holes (4 corners)
    lines.append("T03")
    mount_holes = [(3.5, 3.5), (51.5, 3.5), (51.5, 51.5), (3.5, 51.5)]
    for mhx, mhy in mount_holes:
        lines.append(f"X{int(mhx*1000):+07d}Y{int(mhy*1000):+07d}")

    lines.append("M30")
    return "\n".join(lines)


# ── Main: generate all files and zip ─────────────────────────────────────────

def generate_kagi_lite(outdir: str):
    os.makedirs(outdir, exist_ok=True)

    files = {
        "kagi-lite-F_Cu.gbr":    gen_copper_layer("F.Cu", True, True),
        "kagi-lite-In1_Cu.gbr":  gen_copper_inner(2),  # GND plane
        "kagi-lite-In2_Cu.gbr":  gen_copper_inner(3),  # PWR plane
        "kagi-lite-B_Cu.gbr":    gen_copper_layer("B.Cu", False, False),
        "kagi-lite-F_Mask.gbr":  gen_mask_layer(True),
        "kagi-lite-B_Mask.gbr":  gen_mask_layer(False),
        "kagi-lite-F_SilkS.gbr": gen_silkscreen(True),
        "kagi-lite-B_SilkS.gbr": gen_silkscreen(False),
        "kagi-lite-Edge_Cuts.gbr": gen_edge_cuts(),
        "kagi-lite.drl":          gen_drill_file(),
    }

    print(f"Generating KAGI Lite Gerbers → {outdir}/")
    for fname, content in files.items():
        fpath = os.path.join(outdir, fname)
        with open(fpath, "w") as f:
            f.write(content)
        print(f"  ✓ {fname}  ({len(content):,} bytes)")

    # Create ZIP for JLCPCB upload
    zippath = outdir + ".zip"
    with zipfile.ZipFile(zippath, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in files:
            zf.write(os.path.join(outdir, fname), fname)
    print(f"\n  📦 {zippath}  (JLCPCB Gerber upload)")
    return zippath


# ── KAGI Band (24×12mm 2-layer) ───────────────────────────────────────────────

BAND_CPL = {
    "U1":  (12.0, 6.0,  0),   # ESP32-C3-MINI-1
    "U2":  (4.0,  3.0,  0),   # LIS2DH12
    "U3":  (20.0, 6.0,  0),   # MAX30102
    "U4":  (4.0,  9.0,  0),   # NT3H1101
    "U5":  (20.0, 2.0,  0),   # RT9013 LDO
    "U6":  (8.0,  2.0,  0),   # ETA4054 charger
    "U7":  (4.0,  5.0,  0),   # DW01A protection
    "Q1":  (16.0, 2.0,  0),   # 2N7002 motor FET
    "J1":  (2.0,  6.0,  0),   # USB-C
    "J2":  (22.0, 10.0, 0),   # JST SH 2P battery
    "J3":  (18.0, 10.0, 0),   # JST SH 2P motor
    "SW1": (2.0,  10.5, 0),   # I'm OK 12mm button
    "D1":  (16.0, 6.0,  0),   # WS2812C status LED
    "D2":  (10.0, 2.0,  0),   # 1N4148W flyback
    "R1":  (8.0,  9.0,  0),   # 4.7K SDA pullup
    "R2":  (9.5,  9.0,  0),   # 4.7K SCL pullup
    "R3":  (14.0, 2.0,  0),   # 6K R_PROG
    "R4":  (6.0,  2.0,  0),   # 33Ω LED
    "C1":  (10.0, 9.0,  0),   # 100nF bypass
    "C2":  (11.5, 9.0,  0),   # 100nF bypass
    "C3":  (18.0, 2.0,  0),   # 10μF output
    "C4":  (13.0, 9.0,  0),   # 100nF
}

BAND_FOOTPRINTS = {
    "U1":  lambda: [(0, 0, 13.2, 16.6, "rect")] + [  # ESP32-C3-MINI-1 simplified
        (-6.6 + i * 0.8,  8.3, 0.7, 1.0, "rect") for i in range(17)
    ],
    "U2":  pads_udfn8,   # LIS2DH12 LGA-16 (simplified as UDFN-8)
    "U3":  pads_udfn8,   # MAX30102 OLGA-14 (simplified)
    "U4":  pads_dfn4,    # NT3H1101 XSON-8 (simplified)
    "U5":  pads_sot23_5, # RT9013
    "U6":  pads_sot23_5, # ETA4054
    "U7":  pads_sot23_6, # DW01A
    "Q1":  lambda: [(-1.0, -1.0, 0.6, 0.9, "rect"), (-1.0, 0.0, 0.6, 0.9, "rect"), (1.0, 0.0, 0.6, 0.9, "rect")],  # SOT-23-3
    "J1":  pads_usbc_hro,
    "J2":  pads_jst_ph2,
    "J3":  pads_jst_ph2,
    "SW1": pads_sw_pts125,
    "D1":  pads_ws2812b_2020,
    "D2":  pads_sod123,
    "R1":  pads_0402,
    "R2":  pads_0402,
    "R3":  pads_0402,
    "R4":  pads_0402,
    "C1":  pads_0402,
    "C2":  pads_0402,
    "C3":  pads_0603,
    "C4":  pads_0402,
}

def generate_kagi_band(outdir: str):
    """Generate KAGI Band 24×12mm 2-layer Gerbers."""
    import copy

    BW, BH = 24.0, 12.0
    os.makedirs(outdir, exist_ok=True)

    # Save originals and swap in band data
    orig_cpl = CPL_DATA.copy()
    orig_fp  = COMPONENT_FOOTPRINTS.copy()
    orig_bw  = BOARD_W
    orig_bh  = BOARD_H

    # Monkeypatch globals for band dimensions
    import gen_gerbers as self_mod
    self_mod.CPL_DATA = BAND_CPL
    self_mod.COMPONENT_FOOTPRINTS = BAND_FOOTPRINTS
    self_mod.BOARD_W = BW
    self_mod.BOARD_H = BH

    files = {
        "kagi-band-F_Cu.gbr":      gen_copper_layer("F.Cu", True, True),
        "kagi-band-B_Cu.gbr":      gen_copper_layer("B.Cu", False, False),
        "kagi-band-F_Mask.gbr":    gen_mask_layer(True),
        "kagi-band-B_Mask.gbr":    gen_mask_layer(False),
        "kagi-band-F_SilkS.gbr":   gen_silkscreen(True),
        "kagi-band-B_SilkS.gbr":   gen_silkscreen(False),
        "kagi-band-Edge_Cuts.gbr":  gen_edge_cuts(),
        "kagi-band.drl":            gen_drill_file(),
    }

    # Restore
    self_mod.CPL_DATA = orig_cpl
    self_mod.COMPONENT_FOOTPRINTS = orig_fp
    self_mod.BOARD_W = orig_bw
    self_mod.BOARD_H = orig_bh

    print(f"\nGenerating KAGI Band Gerbers → {outdir}/")
    for fname, content in files.items():
        fpath = os.path.join(outdir, fname)
        with open(fpath, "w") as f:
            f.write(content)
        print(f"  ✓ {fname}  ({len(content):,} bytes)")

    zippath = outdir + ".zip"
    with zipfile.ZipFile(zippath, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname in files:
            zf.write(os.path.join(outdir, fname), fname)
    print(f"\n  📦 {zippath}")
    return zippath


if __name__ == "__main__":
    base = os.path.dirname(os.path.abspath(__file__))
    lite_zip = generate_kagi_lite(os.path.join(base, "gerbers", "kagi-lite"))
    band_zip = generate_kagi_band(os.path.join(base, "gerbers", "kagi-band"))

    print("\n" + "="*60)
    print("JLCPCB 発注準備完了")
    print("="*60)
    print(f"\n[1] KAGI Lite  Gerber ZIP: {lite_zip}")
    print(f"    BOM CSV:  {base}/jlcpcb/kagi-lite/BOM-JLCPCB.csv")
    print(f"    CPL CSV:  {base}/jlcpcb/kagi-lite/CPL-JLCPCB.csv")
    print(f"\n[2] KAGI Band  Gerber ZIP: {band_zip}")
    print(f"    BOM CSV:  {base}/jlcpcb/kagi-band/BOM-JLCPCB.csv")
    print(f"    CPL CSV:  {base}/jlcpcb/kagi-band/CPL-JLCPCB.csv")
    print("\nJLCPCB order URL: https://cart.jlcpcb.com/quote")
