import UIKit
import SwiftUI

/// 月次レポートのPDF生成とCSVエクスポートを担う純粋なサービス層。
/// UIActivityViewController でのシェアまで一貫して処理する。
struct ReportExportService {

    // MARK: - Data model

    struct MonthlyReport {
        let homeName: String
        let period: String       // e.g. "2026年3月"
        let revenue: Int
        let bookingCount: Int
        let occupiedDays: Int
        let totalDays: Int
        let expenses: [(category: String, amount: Int)]

        var totalExpenses: Int { expenses.reduce(0) { $0 + $1.amount } }
        var profit: Int { revenue - totalExpenses }
        var occupancyRate: Double {
            guard totalDays > 0 else { return 0 }
            return Double(occupiedDays) / Double(totalDays)
        }
        var adr: Double {
            guard occupiedDays > 0 else { return 0 }
            return Double(revenue) / Double(occupiedDays)
        }
        var revpar: Double {
            guard totalDays > 0 else { return 0 }
            return Double(revenue) / Double(totalDays)
        }
    }

    // MARK: - PDF

    static func generatePDF(report: MonthlyReport) -> Data {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842) // A4
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { ctx in
            ctx.beginPage()

            // --- Colors ---
            let bgColor   = UIColor(red: 0.04, green: 0.04, blue: 0.07, alpha: 1)
            let goldColor = UIColor(red: 0.91, green: 0.66, blue: 0.22, alpha: 1)
            let greenColor = UIColor(red: 0.06, green: 0.73, blue: 0.51, alpha: 1)
            let redColor  = UIColor(red: 0.94, green: 0.27, blue: 0.27, alpha: 1)
            let white     = UIColor.white
            let subtext   = UIColor(white: 0.6, alpha: 1)

            // Background
            bgColor.setFill()
            UIRectFill(pageRect)

            // Header bar
            goldColor.setFill()
            UIRectFill(CGRect(x: 0, y: 0, width: 595, height: 64))

            // Title in header
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 20),
                .foregroundColor: UIColor.black
            ]
            "KAGI 月次レポート".draw(at: CGPoint(x: 32, y: 20), withAttributes: titleAttrs)

            var y: CGFloat = 84

            // Home name + period
            draw(report.homeName, at: CGPoint(x: 32, y: y),
                 font: .boldSystemFont(ofSize: 16), color: white)
            y += 24
            draw(report.period, at: CGPoint(x: 32, y: y),
                 font: .systemFont(ofSize: 12), color: goldColor)
            y += 36

            // Summary section
            draw("サマリー", at: CGPoint(x: 32, y: y),
                 font: .boldSystemFont(ofSize: 13), color: goldColor)
            y += 20

            let summaryItems: [(String, String, UIColor)] = [
                ("売上合計", "¥\(formatted(report.revenue))", greenColor),
                ("経費合計", "¥\(formatted(report.totalExpenses))", redColor),
                ("利益", "¥\(formatted(report.profit))", report.profit >= 0 ? greenColor : redColor),
                ("予約件数", "\(report.bookingCount)件", white),
                ("稼働率", "\(Int(report.occupancyRate * 100))%", white),
                ("ADR", "¥\(formatted(Int(report.adr)))", white),
                ("RevPAR", "¥\(formatted(Int(report.revpar)))", white),
            ]

            for (label, value, color) in summaryItems {
                // separator line
                UIColor(white: 1, alpha: 0.08).setFill()
                UIRectFill(CGRect(x: 32, y: y + 14, width: 531, height: 1))

                draw(label, at: CGPoint(x: 32, y: y),
                     font: .systemFont(ofSize: 12), color: subtext)
                draw(value, at: CGPoint(x: 340, y: y),
                     font: .boldSystemFont(ofSize: 12), color: color)
                y += 26
            }

            y += 16

            // Expense breakdown
            if !report.expenses.isEmpty {
                draw("経費明細", at: CGPoint(x: 32, y: y),
                     font: .boldSystemFont(ofSize: 13), color: goldColor)
                y += 20

                for (category, amount) in report.expenses {
                    UIColor(white: 1, alpha: 0.08).setFill()
                    UIRectFill(CGRect(x: 32, y: y + 14, width: 531, height: 1))

                    draw(category, at: CGPoint(x: 32, y: y),
                         font: .systemFont(ofSize: 11), color: subtext)
                    draw("¥\(formatted(amount))", at: CGPoint(x: 340, y: y),
                         font: .systemFont(ofSize: 11), color: white)
                    y += 24
                }
            }

            // Footer
            let footerY: CGFloat = 810
            draw("Generated by KAGI · \(report.period)",
                 at: CGPoint(x: 32, y: footerY),
                 font: .systemFont(ofSize: 9), color: subtext)
        }
    }

    // MARK: - CSV

    /// 確定申告用の月次CSVを生成する（収入・経費を行単位で出力）
    static func generateCSV(reports: [MonthlyReport], homeName: String) -> String {
        var lines: [String] = [
            "物件名,期間,売上,経費,利益,稼働率(%),ADR,RevPAR,予約件数"
        ]
        for r in reports {
            let row = [
                r.homeName,
                r.period,
                "\(r.revenue)",
                "\(r.totalExpenses)",
                "\(r.profit)",
                String(format: "%.1f", r.occupancyRate * 100),
                String(format: "%.0f", r.adr),
                String(format: "%.0f", r.revpar),
                "\(r.bookingCount)"
            ].joined(separator: ",")
            lines.append(row)
        }
        lines.append("")
        lines.append("--- 経費明細 ---")
        lines.append("物件名,期間,カテゴリ,金額")
        for r in reports {
            for (cat, amount) in r.expenses {
                lines.append([r.homeName, r.period, cat, "\(amount)"].joined(separator: ","))
            }
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - Share

    static func sharePDF(report: MonthlyReport, from viewController: UIViewController) {
        let data = generatePDF(report: report)
        let filename = "KAGI_Report_\(report.period).pdf"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        try? data.write(to: url)
        let vc = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        vc.popoverPresentationController?.sourceView = viewController.view
        viewController.present(vc, animated: true)
    }

    static func shareCSV(reports: [MonthlyReport], homeName: String, from viewController: UIViewController) {
        let csv = generateCSV(reports: reports, homeName: homeName)
        let filename = "KAGI_\(homeName)_確定申告.csv"
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        try? csv.data(using: .utf8)?.write(to: url)
        let vc = UIActivityViewController(activityItems: [url], applicationActivities: nil)
        vc.popoverPresentationController?.sourceView = viewController.view
        viewController.present(vc, animated: true)
    }

    // MARK: - Helpers

    private static func draw(_ text: String, at point: CGPoint, font: UIFont, color: UIColor) {
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
        text.draw(at: point, withAttributes: attrs)
    }

    private static func formatted(_ value: Int) -> String {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        return f.string(from: NSNumber(value: value)) ?? "\(value)"
    }
}
